/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.io.quarkiverse.langchain4j.quarkus.langchain4j.core)
    api(libs.io.quarkiverse.langchain4j.quarkus.langchain4j.ollama)
    api(libs.io.quarkus.quarkus.arc)
    api(libs.io.quarkus.quarkus.picocli)
    api(libs.dev.langchain4j.langchain4j.jlama)
    api(libs.com.github.tjake.jlama.core)
    api(libs.com.github.tjake.jlama.native)
    api(libs.dev.langchain4j.langchain4j)
    testImplementation(libs.io.quarkus.quarkus.junit5)
}

group = "org.fxapps"
version = "1.0.0-SNAPSHOT"
description = "code-converter-agent"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
